name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = ""

[[kv_namespaces]]
binding = "kv"
id = ""

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
domain = ["example.com"]
admin = "admin@example.com"
jwt_secret = "change-me-to-random-string"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
